Update notes for submitted changes
* Bug 397315 - "<..>" in troubleshooting.xml could cause validation error When running "validate" on "/assessment/cm/support/troubleshooting.xml", an error "The value of attribute "regexp" associated with an element type "error" must not contain the '<' character." reported on line, 	<error type="AppBehavior" regexp="expected:<400> but was:<500>"> 		 <rootcause>Product Defect</rootcause> 			 	     <action>Submit defect against the OSLC provider</action> 	 	</error>