Bug 397315 - "<..>" in troubleshooting.xml could cause validation error When running "validate" on "/assessment/cm/support/troubleshooting.xml", an error "The value of attribute "regexp" associated with an element type "error" must not contain the '<' character." reported on line, 	<error type="AppBehavior" regexp="expected:<400> but was:<500>"> 		 <rootcause>Product Defect</rootcause> 	     <action>Submit defect against the OSLC provider</action> 	</error>
It is caused by the "<" in regexp="expected:<400> but was:<500>".
Updating it as regexp="expected:&lt;400&gt; but was:&lt;500&gt;" can fix
the problem.

Change-Id: I0a45f43006bce24162ad491faf5ff02738adeeee
Signed-off-by: wangfcdl <wangfcdl@cn.ibm.com>